stages:
  - gradletry
  - androidtry

maven-build:   #this is a JOB
  stage: gradletry
  tags:
    - springboot_tag  # this is LINK to the shell runner on the remote-server 
  script:
    - cd Backend/scribbleshare
    - chmod +x gradlew
    - ./gradlew build

android-build: #this is another job
  image: javiersantos/android-ci:latest      # this is a directive to DOCKER
  stage: androidtry
  tags:
   - android_tag         #this is LINK to the docker runner on the remote-server        
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
    - yum install java-11-openjdk
    - whereis java
  script:
    - cd Frontend
    - ./gradlew --version
    - ./gradlew build
  artifacts: 
    paths:
      - Android_test/app/build/outputs
