stages:
  - gradletry

maven-build:   #this is a JOB
  stage: gradletry
  tags:
    - springboot_tag  # this is LINK to the shell runner on the remote-server 
  script:
    - cd Backend/scribbleshare
    - chmod +x gradlew
    - ./gradlew build
