stages:
  - springbuild
  - springtest
  - androidbuild
  - androidtest

spring-build:   #this is a JOB
  stage: springbuild
  tags:
    - springboot_tag  # this is LINK to the shell runner on the remote-server 
  script:
    - cd Backend/scribbleshare
    - chmod +x gradlew
    - ./gradlew build

spring-test:
  stage: springtest
  tags:
    - springboot_tag
  script:
    - cd Backend/scribbleshare
    - chmod +x gradlew
    - ./gradlew test
  artifacts:
    paths:
      - Backend/target/*.jar


android-build: #this is another job
  image: javiersantos/android-ci:latest      # this is a directive to DOCKER
  stage: androidbuild
  tags:
   - android_tag         #this is LINK to the docker runner on the remote-server        
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend
    - ./gradlew assemble
  artifacts:
    paths:
    - Android_test/app/build/outputs/

android-test:
  image: javiersantos/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  tags:
   - android_tag
  script:
    - cd Frontend
    - ./gradlew test
